---
########################
# Include OS variables #
########################
- name: Include OS variables
  include_vars: "../vars/main.yml"
  tags: main

##########
# cygwin #
##########
- name: Test if Cygwin is already installed
  win_stat:
    path: 'C:\cygwin64'
  register: cygwin_installed
  tags: cygwin

# For details about the cache, see: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1210#issuecomment-679076545
- name: Retrieve cygwin cache from ci.adoptopenjdk.net
  win_get_url:
    url: https://ci.adoptopenjdk.net/userContent/winansible/cygwin64.tar.gz
    dest: C:/temp/cygwin64.tar.gz
    checksum: 8f8b1d7d00233e384e725390c4018941fe7125290b94ecc0eeb3cf6684b4ce23
    checksum_algorithm: sha256
  when: (not cygwin_installed.stat.exists)
  tags: cygwin

- name: Retrieve cygwin toolset from ci.adoptopenjdk.net
  win_get_url:
    url: https://ci.adoptopenjdk.net/userContent/winansible/cygwin64_bootstrap.zip
    dest: C:/temp/cyg_toolset.zip
    checksum: d7950df964a0618ac47561d349276d4644e27f5b8f0a5fba9b10db702d09ecad
    checksum_algorithm: sha256
  when: (not cygwin_installed.stat.exists)
  tags: cygwin

- name: Use cygwin 'tar' and 'pigz' to extract cygwin cache
  win_shell: |
    New-Item -ItemType directory -Name cygwin_toolset -Path C:\temp\
    Expand-Archive -LiteralPath C:\temp\cyg_toolset.zip -DestinationPath C:\temp\cygwin_toolset;
    $env:path="C:\temp\cygwin_toolset;$env:path"
    cd C:\
    tar --force-local -I pigz -xf C:\temp\cygwin64.tar.gz
  args:
    executable: powershell
  when: (not cygwin_installed.stat.exists)
  tags: cygwin

- name: Change git config to not replace Line endings
  win_shell: "C:/cygwin64/bin/git config --system core.autocrlf false"
  tags: cygwin

- name: Remove c:\cygwin64\bin from the path if it exists
  win_path:
    name: PATH
    elements:
      - 'C:\cygwin64\bin'
    scope: machine
    state: absent
  when: (not cygwin_installed.stat.exists)
  tags: cygwin

- name: Add C:\cygwin64\bin to the front of the path
  win_shell: |
    [Environment]::SetEnvironmentVariable("Path", "C:\cygwin64\bin;" + $env:Path, [System.EnvironmentVariableTarget]::Machine)
  args:
    executable: powershell
  when: (not cygwin_installed.stat.exists)
  tags: cygwin

- name: Reboot machine for PATH changes to take effect
  win_reboot:
    reboot_timeout: 1800
  when: (not cygwin_installed.stat.exists)
  tags: cygwin
